import {useState} from 'react'
import {Icon} from './Icon'
import {closeFiscalYear,deleteDemo} from '../api'
import {errorText} from '../lib/errors'
const groups=[['general','عمومی','تنظیمات پایه برنامه'],['company','شرکت و شعب','اطلاعات شرکت، شعب و سال مالی'],['security','امنیت و کاربران','کاربران، نقش‌ها و دسترسی‌ها'],['accounting','حسابداری','کدینگ، اسناد و کنترل‌های مالی'],['sales','فروش و خرید','فاکتور، قیمت، مالیات و تسویه'],['inventory','انبار','انبارها، موجودی و روش ارزش‌گذاری'],['treasury','خزانه و چک','صندوق، بانک و چرخه چک'],['printing','چاپ','قالب فاکتور، رسید و گزارش'],['backup','پشتیبان‌گیری','نسخه پشتیبان و بازیابی'],['integrations','اتصالات','API، افزونه و سخت‌افزار'],['appearance','ظاهر','زبان، تم و چیدمان'],['data','داده‌ها','داده نمونه و مدیریت اطلاعات']]
export function SettingsCenter({onClose,dark,setDark}:{onClose:()=>void,dark:boolean,setDark:(v:boolean)=>void}){
 const [active,setActive]=useState('general'); const [demoBusy,setDemoBusy]=useState(false); const [fyBusy,setFyBusy]=useState(false); const [message,setMessage]=useState('')
 const runDemo=async()=>{if(!confirm('تمام داده‌های نمونه حذف می‌شوند. ادامه می‌دهید؟'))return;setDemoBusy(true);try{await deleteDemo();setMessage('داده‌های نمونه حذف شد.')}catch(e){setMessage(errorText(e))}finally{setDemoBusy(false)}}
 const closeFY=async()=>{if(!confirm('بستن سال مالی برگشت‌پذیر نیست. ادامه می‌دهید؟'))return;setFyBusy(true);try{await closeFiscalYear();setMessage('سال مالی بسته شد.')}catch(e){setMessage(errorText(e))}finally{setFyBusy(false)}}
 return <div className="settings-overlay"><aside className="settings-nav"><div className="settings-brand"><button className="icon-btn" onClick={onClose}><Icon name="close"/></button><div><b>مرکز تنظیمات</b><span>کنترل کامل برنامه</span></div></div>{groups.map(g=><button key={g[0]} className={active===g[0]?'setting-nav active':'setting-nav'} onClick={()=>setActive(g[0])}><span><b>{g[1]}</b><small>{g[2]}</small></span><Icon name="chevron" size={14}/></button>)}</aside><section className="settings-content"><header><div><div className="eyebrow">SETTINGS CENTER</div><h1>{groups.find(g=>g[0]===active)?.[1]}</h1><p>{groups.find(g=>g[0]===active)?.[2]}</p></div><button className="icon-btn" onClick={onClose}><Icon name="close"/></button></header>{message&&<div className="success-box">{message}</div>}
 {active==='general'&&<div className="settings-grid"><Setting title="زبان برنامه" desc="زبان پیش‌فرض رابط کاربری" value="فارسی (RTL)"/><Setting title="واحد پول" desc="واحد داخلی محاسبات مالی" value="ریال"/><Setting title="تقویم" desc="تقویم نمایش داده‌ها" value="شمسی"/><div className="setting-card"><div><b>حالت نمایش</b><span>ظاهر برنامه</span></div><button className="theme-toggle" onClick={()=>setDark(!dark)}><Icon name={dark?'sun':'moon'}/>{dark?'تاریک':'روشن'}</button></div></div>}
 {active==='data'&&<div className="settings-stack"><div className="setting-card danger-card"><div><b>حذف داده‌های نمونه</b><span>فقط داده‌های Demo را حذف می‌کند. داده واقعی کاربر نباید با آن مخلوط شود.</span></div><button className="danger" disabled={demoBusy} onClick={runDemo}>{demoBusy?'در حال انجام...':'حذف داده‌های نمونه'}</button></div></div>}
 {active==='company'&&<div className="settings-stack"><div className="setting-card"><div><b>سال مالی فعال</b><span>ثبت عملیات مالی فقط در دوره باز و معتبر مجاز است.</span></div><button className="secondary" disabled={fyBusy} onClick={closeFY}>{fyBusy?'در حال بررسی...':'بستن سال مالی'}</button></div></div>}
 {!['general','data','company'].includes(active)&&<div className="settings-grid">{['تنظیمات پایه','دسترسی کاربران','اعتبارسنجی','ثبت تغییرات','پیش‌فرض‌ها','کنترل عملیات'].map((x,i)=><div className="setting-card" key={i}><div><b>{x}</b><span>این بخش برای اتصال به تنظیمات واقعی ماژول آماده است.</span></div><span className="status pending">آماده توسعه</span></div>)}</div>}
 </section></div>
}
function Setting({title,desc,value}:{title:string,desc:string,value:string}){return <div className="setting-card"><div><b>{title}</b><span>{desc}</span></div><strong>{value}</strong></div>}
