import {useEffect,useMemo,useState} from 'react'
import {Icon} from '../components/Icon'
import {getProducts,getWarehouses,getInventoryAdvanced,getInventoryValuationMethod,setInventoryValuationMethod,getInventoryLots,createInventoryLot,getInventoryCounts,createInventoryCount,postInventoryCount,getInventoryTransferOrders,receiveInventoryTransfer,Product,Warehouse,InventoryAdvanced,InventoryLot,InventoryCount,InventoryTransferOrder} from '../api'
import {errorText} from '../lib/errors'
import {formatRials as money, formatNumber as n, todayJalali} from '../lib/format'
import {useI18n} from '../lib/i18n'
import {Select} from '../components/Select'
export function AdvancedInventory(){const {t}=useI18n();
 const [products,setProducts]=useState<Product[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[rows,setRows]=useState<InventoryAdvanced[]>([]),[lots,setLots]=useState<InventoryLot[]>([]),[counts,setCounts]=useState<InventoryCount[]>([]),[transfers,setTransfers]=useState<InventoryTransferOrder[]>([]),[method,setMethod]=useState('weighted_average'),[tab,setTab]=useState<'stock'|'lots'|'counts'|'transfers'>('stock'),[q,setQ]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<'lot'|'count'|'method'|null>(null)
 const load=async()=>{setError('');try{const [p,w,r,m,l,c,t]=await Promise.all([getProducts(),getWarehouses(),getInventoryAdvanced(),getInventoryValuationMethod(),getInventoryLots(),getInventoryCounts(),getInventoryTransferOrders()]);setProducts(p);setWarehouses(w);setRows(r);setMethod(m);setLots(l);setCounts(c);setTransfers(t)}catch(e){setError(errorText(e))}}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>rows.filter(x=>{const p=products.find(y=>y.id===x.product_id)?.name||'';const w=warehouses.find(y=>y.id===x.warehouse_id)?.name||'';return `${p} ${w}`.includes(q.trim())}),[rows,products,warehouses,q])
 const totalValue=rows.reduce((a,x)=>a+x.inventory_value,0),totalQty=rows.reduce((a,x)=>a+x.quantity,0),reserved=rows.reduce((a,x)=>a+x.reserved_quantity,0),expiring=rows.reduce((a,x)=>a+x.expiring_quantity,0)
 const submitLot=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');try{const f=new FormData(e.currentTarget);await createInventoryLot(String(f.get('product')),String(f.get('warehouse')),String(f.get('lot')),String(f.get('type')) as any,String(f.get('serial')||'')||undefined,String(f.get('mfg')||'')||undefined,String(f.get('expiry')||'')||undefined,Number(f.get('qty')),Number(f.get('cost')));setSuccess(t('inv.lotSaved'));setModal(null);await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 const createCount=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget);await createInventoryCount(String(f.get('warehouse')),String(f.get('title')),String(f.get('date')));setSuccess(t('inv.countCreated'));setModal(null);await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 const changeMethod=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget);await setInventoryValuationMethod(String(f.get('method')) as any);setSuccess(t('inv.methodSaved'));setModal(null);await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <section className="page"><div className="page-head"><div><div className="eyebrow">{t('inv.title')}</div><h1>{t('inv.title')}</h1><p>{t('inv.subtitle')}</p></div><div className="quick-actions-inline"><button className="secondary" onClick={()=>setModal('method')}>روش ارزش‌گذاری: {method==='fifo'?'FIFO':method==='moving_average'?t('inv.movingAverage'):t('inv.weightedAverage')}</button><button className="secondary" onClick={()=>setModal('lot')}>{t('inv.serialBatch')}</button><button className="primary" onClick={()=>setModal('count')}>{t('inv.newCount')}</button></div></div>
 {error&&<div className="error-box">{error}</div>}{success&&<div className="success-box">{success}</div>}
 <div className="kpi-grid"><div className="kpi"><span>{t('inv.stockCount')}</span><b>{n(totalQty)}</b></div><div className="kpi"><span>{t('inv.reservedQty')}</span><b>{n(reserved)}</b></div><div className="kpi"><span>{t('inv.stockValue')}</span><b>{money(totalValue)}</b></div><div className="kpi"><span>{t('inv.expiring')}</span><b>{n(expiring)}</b></div></div>
 <div className="panel list-panel"><div className="toolbar"><div className="tabs"><button className={tab==='stock'?'active':''} onClick={()=>setTab('stock')}>{t('inv.tab.valuation')}</button><button className={tab==='lots'?'active':''} onClick={()=>setTab('lots')}>{t('inv.tab.lots')}</button><button className={tab==='counts'?'active':''} onClick={()=>setTab('counts')}>{t('inv.tab.counts')}</button><button className={tab==='transfers'?'active':''} onClick={()=>setTab('transfers')}>{t('inv.tab.transit')}</button></div><div className="global-search inner"><Icon name="search" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t('ops.searchDots')}/></div><button aria-label={t('common.refresh')} className="icon-btn" onClick={load}><Icon name="refresh"/></button></div>
 {tab==='stock'&&<div className="table-wrap"><table className="large-table"><thead><tr><th>{t('invoiceForm.product')}</th><th>{t('common.warehouse')}</th><th>{t('products.stock')}</th><th>{t('ops.reserved')}</th><th>{t('inv.inTransit')}</th><th>{t('ops.available')}</th><th>{t('ops.unitCost')}</th><th>{t('reports.value')}</th><th>{t('inv.expiry30')}</th></tr></thead><tbody>{filtered.map(r=><tr key={r.product_id+r.warehouse_id}><td><b>{products.find(p=>p.id===r.product_id)?.name||r.product_id}</b></td><td>{warehouses.find(w=>w.id===r.warehouse_id)?.name||r.warehouse_id}</td><td>{n(r.quantity)}</td><td>{n(r.reserved_quantity)}</td><td>{n(r.in_transit_quantity)}</td><td>{n(r.available_quantity)}</td><td>{money(r.average_cost)}</td><td>{money(r.inventory_value)}</td><td className={r.expiring_quantity>0?'red-text':''}>{n(r.expiring_quantity)}</td></tr>)}</tbody></table></div>}
 {tab==='lots'&&<div className="table-wrap"><table className="large-table"><thead><tr><th>{t('common.type')}</th><th>{t('invoiceForm.product')}</th><th>{t('common.warehouse')}</th><th>Lot</th><th>{t('inv.serial')}</th><th>{t('inv.expiry')}</th><th>{t('common.quantity')}</th><th>{t('common.status')}</th></tr></thead><tbody>{lots.filter(x=>`${x.lot_number} ${x.serial_number||''}`.includes(q.trim())).map(x=><tr key={x.id}><td>{x.lot_type==='serial'?t('inv.serial'):t('inv.batch')}</td><td>{products.find(p=>p.id===x.product_id)?.name||x.product_id}</td><td>{warehouses.find(w=>w.id===x.warehouse_id)?.name||x.warehouse_id}</td><td>{x.lot_number}</td><td>{x.serial_number||'—'}</td><td>{x.expiry_date||'—'}</td><td>{n(x.quantity)}</td><td>{x.status}</td></tr>)}</tbody></table></div>}
 {tab==='counts'&&<div className="table-wrap"><table className="large-table"><thead><tr><th>{t('partyForm.titlePrefix')}</th><th>{t('common.warehouse')}</th><th>{t('common.date')}</th><th>{t('inv.items')}</th><th>{t('inv.difference')}</th><th>{t('common.status')}</th><th></th></tr></thead><tbody>{counts.map(x=><tr key={x.id}><td>{x.title}</td><td>{warehouses.find(w=>w.id===x.warehouse_id)?.name||x.warehouse_id}</td><td>{x.count_date}</td><td>{n(x.line_count)}</td><td>{n(x.variance_count)}</td><td>{x.status}</td><td>{['counting','review'].includes(x.status)&&<button className="table-action" onClick={async()=>{try{await postInventoryCount(x.id);setSuccess(t('inv.countPosted'));await load()}catch(e){setError(errorText(e))}}}>{t('inv.finalize')}</button>}</td></tr>)}</tbody></table></div>}
 {tab==='transfers'&&<div className="table-wrap"><table className="large-table"><thead><tr><th>{t('invoiceForm.product')}</th><th>{t('inv.source')}</th><th>{t('inv.destination')}</th><th>{t('common.quantity')}</th><th>{t('inv.cost')}</th><th>{t('common.status')}</th><th></th></tr></thead><tbody>{transfers.map(x=><tr key={x.id}><td>{products.find(p=>p.id===x.product_id)?.name||x.product_id}</td><td>{warehouses.find(w=>w.id===x.from_warehouse_id)?.name||x.from_warehouse_id}</td><td>{warehouses.find(w=>w.id===x.to_warehouse_id)?.name||x.to_warehouse_id}</td><td>{n(x.quantity)}</td><td>{money(x.unit_cost)}</td><td>{x.status}</td><td>{x.status==='in_transit'&&<button className="table-action" onClick={async()=>{try{await receiveInventoryTransfer(x.id);setSuccess(t('inv.transferReceived'));await load()}catch(e){setError(errorText(e))}}}>{t('inv.receive')}</button>}</td></tr>)}</tbody></table></div>}</div>
 {modal&&<div className="modal-backdrop" role="presentation"><form className="modal form-modal" onSubmit={modal==='lot'?submitLot:modal==='count'?createCount:changeMethod}><div className="modal-head"><div><div className="eyebrow">{t('inv.sensitive')}</div><h2>{modal==='lot'?t('inv.recordLot'):modal==='count'?t('inv.newCount'):t('inv.valuationMethod')}</h2></div><button aria-label={t('common.actions')} type="button" className="icon-btn" onClick={()=>setModal(null)}><Icon name="close"/></button></div>{modal==='lot'?<div className="form-grid"><label>{t('invoiceForm.product')}<Select name="product" required defaultValue=""><option value="" disabled>{t('invoiceForm.selectPlaceholder')}</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</Select></label><label>{t('common.warehouse')}<Select name="warehouse" required defaultValue=""><option value="" disabled>{t('invoiceForm.selectPlaceholder')}</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.code} — {w.name}</option>)}</Select></label><label>{t('common.type')}<Select name="type"><option value="batch">{t('inv.batchNumber')}</option><option value="serial">{t('inv.serialNumber')}</option></Select></label><label>{t('inv.lotNumber')}<input name="lot" required/></label><label>{t('inv.serialNumber')}<input name="serial"/></label><label>{t('inv.productionDate')}<input name="mfg" placeholder="1405/01/01"/></label><label>{t('inv.expiryDate')}<input name="expiry" placeholder="1406/01/01"/></label><label>{t('common.quantity')}<input name="qty" type="number" min="0" step="0.001" required/></label><label>{t('ops.unitCost')}<input name="cost" type="number" min="0" required/></label></div>:modal==='count'?<div className="form-grid"><label>{t('common.warehouse')}<Select name="warehouse" required defaultValue=""><option value="" disabled>{t('invoiceForm.selectPlaceholder')}</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.code} — {w.name}</option>)}</Select></label><label>{t('partyForm.titlePrefix')}<input name="title" required/></label><label>{t('common.date')}<input name="date" defaultValue={todayJalali()} placeholder="1405/01/01" required/></label></div>:<div className="form-grid"><label>{t('inv.method')}<Select name="method" defaultValue={method}><option value="fifo">{t('inv.fifo')}</option><option value="moving_average">{t('inv.movingAverage')}</option><option value="weighted_average">{t('inv.weightedAverage')}</option></Select></label></div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(null)}>{t('common.cancel')}</button><button className="primary" disabled={busy}>{busy?t('ops.posting'):t('dataPage.saveAction')}</button></div></form></div>}
 </section>
}
