import {useEffect,useMemo,useState} from 'react'
import {Icon} from '../components/Icon'
import {getProducts,getWarehouses,getInventoryAdvanced,getInventoryValuationMethod,setInventoryValuationMethod,getInventoryLots,createInventoryLot,getInventoryCounts,createInventoryCount,postInventoryCount,getInventoryTransferOrders,receiveInventoryTransfer,Product,Warehouse,InventoryAdvanced,InventoryLot,InventoryCount,InventoryTransferOrder} from '../api'
import {errorText} from '../lib/errors'
import {formatRials as money, formatNumber as n, todayJalali} from '../lib/format'
export function AdvancedInventory(){
 const [products,setProducts]=useState<Product[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[rows,setRows]=useState<InventoryAdvanced[]>([]),[lots,setLots]=useState<InventoryLot[]>([]),[counts,setCounts]=useState<InventoryCount[]>([]),[transfers,setTransfers]=useState<InventoryTransferOrder[]>([]),[method,setMethod]=useState('weighted_average'),[tab,setTab]=useState<'stock'|'lots'|'counts'|'transfers'>('stock'),[q,setQ]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<'lot'|'count'|'method'|null>(null)
 const load=async()=>{setError('');try{const [p,w,r,m,l,c,t]=await Promise.all([getProducts(),getWarehouses(),getInventoryAdvanced(),getInventoryValuationMethod(),getInventoryLots(),getInventoryCounts(),getInventoryTransferOrders()]);setProducts(p);setWarehouses(w);setRows(r);setMethod(m);setLots(l);setCounts(c);setTransfers(t)}catch(e){setError(errorText(e))}}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>rows.filter(x=>{const p=products.find(y=>y.id===x.product_id)?.name||'';const w=warehouses.find(y=>y.id===x.warehouse_id)?.name||'';return `${p} ${w}`.includes(q.trim())}),[rows,products,warehouses,q])
 const totalValue=rows.reduce((a,x)=>a+x.inventory_value,0),totalQty=rows.reduce((a,x)=>a+x.quantity,0),reserved=rows.reduce((a,x)=>a+x.reserved_quantity,0),expiring=rows.reduce((a,x)=>a+x.expiring_quantity,0)
 const submitLot=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');try{const f=new FormData(e.currentTarget);await createInventoryLot(String(f.get('product')),String(f.get('warehouse')),String(f.get('lot')),String(f.get('type')) as any,String(f.get('serial')||'')||undefined,String(f.get('mfg')||'')||undefined,String(f.get('expiry')||'')||undefined,Number(f.get('qty')),Number(f.get('cost')));setSuccess('Lot با موفقیت ثبت شد.');setModal(null);await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 const createCount=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget);await createInventoryCount(String(f.get('warehouse')),String(f.get('title')),String(f.get('date')));setSuccess('دوره انبارگردانی ایجاد شد.');setModal(null);await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 const changeMethod=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget);await setInventoryValuationMethod(String(f.get('method')) as any);setSuccess('روش ارزش‌گذاری ذخیره شد.');setModal(null);await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <section className="page"><div className="page-head"><div><div className="eyebrow">ADVANCED INVENTORY</div><h1>انبار پیشرفته</h1><p>ارزش‌گذاری، رزرو، سری و بچ، انبارگردانی و انتقال در راه.</p></div><div className="quick-actions-inline"><button className="secondary" onClick={()=>setModal('method')}>روش ارزش‌گذاری: {method==='fifo'?'FIFO':method==='moving_average'?'میانگین متحرک':'میانگین موزون'}</button><button className="secondary" onClick={()=>setModal('lot')}>سری / بچ</button><button className="primary" onClick={()=>setModal('count')}>انبارگردانی جدید</button></div></div>
 {error&&<div className="error-box">{error}</div>}{success&&<div className="success-box">{success}</div>}
 <div className="kpi-grid"><div className="kpi"><span>تعداد موجودی</span><b>{n(totalQty)}</b></div><div className="kpi"><span>رزرو شده</span><b>{n(reserved)}</b></div><div className="kpi"><span>ارزش موجودی</span><b>{money(totalValue)}</b></div><div className="kpi"><span>در معرض انقضا</span><b>{n(expiring)}</b></div></div>
 <div className="panel list-panel"><div className="toolbar"><div className="tabs"><button className={tab==='stock'?'active':''} onClick={()=>setTab('stock')}>موجودی و ارزش‌گذاری</button><button className={tab==='lots'?'active':''} onClick={()=>setTab('lots')}>سری و بچ</button><button className={tab==='counts'?'active':''} onClick={()=>setTab('counts')}>انبارگردانی</button><button className={tab==='transfers'?'active':''} onClick={()=>setTab('transfers')}>انتقال در راه</button></div><div className="global-search inner"><Icon name="search" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجو..."/></div><button aria-label="بروزرسانی" className="icon-btn" onClick={load}><Icon name="refresh"/></button></div>
 {tab==='stock'&&<div className="table-wrap"><table className="large-table"><thead><tr><th>کالا</th><th>انبار</th><th>موجودی</th><th>رزرو</th><th>در راه</th><th>قابل فروش</th><th>بهای واحد</th><th>ارزش</th><th>انقضای ۳۰ روز</th></tr></thead><tbody>{filtered.map(r=><tr key={r.product_id+r.warehouse_id}><td><b>{products.find(p=>p.id===r.product_id)?.name||r.product_id}</b></td><td>{warehouses.find(w=>w.id===r.warehouse_id)?.name||r.warehouse_id}</td><td>{n(r.quantity)}</td><td>{n(r.reserved_quantity)}</td><td>{n(r.in_transit_quantity)}</td><td>{n(r.available_quantity)}</td><td>{money(r.average_cost)}</td><td>{money(r.inventory_value)}</td><td className={r.expiring_quantity>0?'red-text':''}>{n(r.expiring_quantity)}</td></tr>)}</tbody></table></div>}
 {tab==='lots'&&<div className="table-wrap"><table className="large-table"><thead><tr><th>نوع</th><th>کالا</th><th>انبار</th><th>Lot</th><th>سریال</th><th>انقضا</th><th>مقدار</th><th>وضعیت</th></tr></thead><tbody>{lots.filter(x=>`${x.lot_number} ${x.serial_number||''}`.includes(q.trim())).map(x=><tr key={x.id}><td>{x.lot_type==='serial'?'سریال':'بچ'}</td><td>{products.find(p=>p.id===x.product_id)?.name||x.product_id}</td><td>{warehouses.find(w=>w.id===x.warehouse_id)?.name||x.warehouse_id}</td><td>{x.lot_number}</td><td>{x.serial_number||'—'}</td><td>{x.expiry_date||'—'}</td><td>{n(x.quantity)}</td><td>{x.status}</td></tr>)}</tbody></table></div>}
 {tab==='counts'&&<div className="table-wrap"><table className="large-table"><thead><tr><th>عنوان</th><th>انبار</th><th>تاریخ</th><th>اقلام</th><th>اختلاف</th><th>وضعیت</th><th></th></tr></thead><tbody>{counts.map(x=><tr key={x.id}><td>{x.title}</td><td>{warehouses.find(w=>w.id===x.warehouse_id)?.name||x.warehouse_id}</td><td>{x.count_date}</td><td>{n(x.line_count)}</td><td>{n(x.variance_count)}</td><td>{x.status}</td><td>{['counting','review'].includes(x.status)&&<button className="table-action" onClick={async()=>{try{await postInventoryCount(x.id);setSuccess('انبارگردانی ثبت نهایی شد.');await load()}catch(e){setError(errorText(e))}}}>ثبت نهایی</button>}</td></tr>)}</tbody></table></div>}
 {tab==='transfers'&&<div className="table-wrap"><table className="large-table"><thead><tr><th>کالا</th><th>مبدأ</th><th>مقصد</th><th>مقدار</th><th>بها</th><th>وضعیت</th><th></th></tr></thead><tbody>{transfers.map(x=><tr key={x.id}><td>{products.find(p=>p.id===x.product_id)?.name||x.product_id}</td><td>{warehouses.find(w=>w.id===x.from_warehouse_id)?.name||x.from_warehouse_id}</td><td>{warehouses.find(w=>w.id===x.to_warehouse_id)?.name||x.to_warehouse_id}</td><td>{n(x.quantity)}</td><td>{money(x.unit_cost)}</td><td>{x.status}</td><td>{x.status==='in_transit'&&<button className="table-action" onClick={async()=>{try{await receiveInventoryTransfer(x.id);setSuccess('انتقال دریافت شد.');await load()}catch(e){setError(errorText(e))}}}>دریافت</button>}</td></tr>)}</tbody></table></div>}</div>
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><form className="modal form-modal" onSubmit={modal==='lot'?submitLot:modal==='count'?createCount:changeMethod} onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">عملیات حساس انبار</div><h2>{modal==='lot'?'ثبت سری / بچ':modal==='count'?'انبارگردانی جدید':'روش ارزش‌گذاری'}</h2></div><button aria-label="عملیات" type="button" className="icon-btn" onClick={()=>setModal(null)}><Icon name="close"/></button></div>{modal==='lot'?<div className="form-grid"><label>کالا<select name="product" required defaultValue=""><option value="" disabled>انتخاب کنید…</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select></label><label>انبار<select name="warehouse" required defaultValue=""><option value="" disabled>انتخاب کنید…</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.code} — {w.name}</option>)}</select></label><label>نوع<select name="type"><option value="batch">سری ساخت (بچ)</option><option value="serial">شماره سریال</option></select></label><label>شماره Lot<input name="lot" required/></label><label>شماره سریال<input name="serial"/></label><label>تاریخ تولید<input name="mfg" placeholder="1405/01/01"/></label><label>تاریخ انقضا<input name="expiry" placeholder="1406/01/01"/></label><label>مقدار<input name="qty" type="number" min="0" step="0.001" required/></label><label>بهای واحد<input name="cost" type="number" min="0" required/></label></div>:modal==='count'?<div className="form-grid"><label>انبار<select name="warehouse" required defaultValue=""><option value="" disabled>انتخاب کنید…</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.code} — {w.name}</option>)}</select></label><label>عنوان<input name="title" required/></label><label>تاریخ<input name="date" defaultValue={todayJalali()} placeholder="1405/01/01" required/></label></div>:<div className="form-grid"><label>روش<select name="method" defaultValue={method}><option value="fifo">اولین صادره از اولین وارده</option><option value="moving_average">میانگین متحرک</option><option value="weighted_average">میانگین موزون</option></select></label></div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(null)}>انصراف</button><button className="primary" disabled={busy}>{busy?'در حال ثبت...':'ثبت'}</button></div></form></div>}
 </section>
}
