import {useState} from 'react'
import {Icon} from '../components/Icon'
import {importData} from '../api'
import {errorText} from '../lib/errors'

type Entity='contacts'|'products'
export function DataTools(){
 const [entity,setEntity]=useState<Entity>('contacts'); const [rows,setRows]=useState<Record<string,unknown>[]>([]); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState(''); const [error,setError]=useState('')
 const read=(file:File)=>{setError('');setMsg('');const r=new FileReader();r.onload=()=>{try{const text=String(r.result||'');const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error('فایل باید حداقل یک ردیف داده داشته باشد.');const headers=lines[0].split(',').map(x=>x.trim().replace(/^"|"$/g,''));const parsed=lines.slice(1).map(line=>{const vals=line.split(',').map(x=>x.trim().replace(/^"|"$/g,''));return Object.fromEntries(headers.map((h,i)=>[h,vals[i]??'']))});setRows(parsed);setMsg(`${parsed.length} ردیف برای بررسی آماده شد.`)}catch(e){setError(errorText(e))}};r.readAsText(file,'utf-8')}
 const commit=async()=>{if(!rows.length)return;setBusy(true);setError('');try{await importData(entity,rows);setMsg(`${rows.length} ردیف با موفقیت وارد شد.`);setRows([])}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <section className="page"><div className="page-head"><div><div className="eyebrow">ورود و خروج اطلاعات</div><h1>ورود و خروج اطلاعات</h1><p>قبل از ثبت، داده‌ها را بررسی کنید. عملیات ورود در یک تراکنش انجام می‌شود.</p></div></div>{error&&<div className="error-box">{error}</div>}{msg&&<div className="success-box">{msg}</div>}<div className="panel"><div className="builder-section"><label>نوع داده<select value={entity} onChange={e=>{setEntity(e.target.value as Entity);setRows([])}}><option value="contacts">اشخاص</option><option value="products">کالاها</option></select></label><label>فایل CSV<input type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&read(e.target.files[0])}/></label></div><div className="import-format"><b>قالب پیشنهادی</b><span>{entity==='contacts'?'name,kind,mobile,is_customer,is_supplier':'sku,barcode,name,unit,sale_price,purchase_price,min_stock'}</span></div>{rows.length>0&&<><div className="panel-head"><h3>پیش‌نمایش</h3><span>{rows.length} ردیف</span></div><div className="table-wrap"><table className="large-table"><thead><tr>{Object.keys(rows[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,50).map((r,i)=><tr key={i}>{Object.keys(rows[0]).map(k=><td key={k}>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div><button className="primary" disabled={busy} onClick={commit}>{busy?'در حال ورود...':'تأیید و ورود اطلاعات'}</button></>}</div></section>
}
