import {useEffect,useMemo,useState} from 'react'
import {Icon} from '../components/Icon'
import {getAccounts,getContacts,getJournals,getProducts,createContact,createProduct,updateContact,updateProduct,deleteContact,deleteProduct,createJournal,Account,Contact,Product,Journal} from '../api'
import {errorText} from '../lib/errors'
import {formatRials as money, formatNumber as n} from '../lib/format'
import {useI18n} from '../lib/i18n'
import {Select} from '../components/Select'

type Props={kind:'contacts'|'products'|'accounts'|'journals'}
export function DataPage({kind}:Props){const {t}=useI18n();
 const [contacts,setContacts]=useState<Contact[]>([]),[products,setProducts]=useState<Product[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[journals,setJournals]=useState<Journal[]>([])
 const [q,setQ]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState<Contact|Product|null>(null)
 const load=async()=>{setError('');try{if(kind==='contacts')setContacts(await getContacts());if(kind==='products')setProducts(await getProducts());if(kind==='accounts')setAccounts(await getAccounts());if(kind==='journals')setJournals(await getJournals())}catch(e){setError(errorText(e))}}
 useEffect(()=>{load()},[kind])
 const title={contacts:t('page.parties'),products:t('productForm.eyebrow'),accounts:t('coa.title'),journals:t('nav.journals')}[kind]
 const rows=useMemo(()=>{const s=q.trim();if(kind==='contacts')return contacts.filter(x=>(x.name+' '+(x.mobile||'')).includes(s));if(kind==='products')return products.filter(x=>(x.name+' '+x.sku+' '+(x.barcode||'')).includes(s));if(kind==='accounts')return accounts.filter(x=>(x.code+' '+x.name).includes(s));return journals.filter(x=>`${x.number} ${x.description}`.includes(s))},[kind,q,contacts,products,accounts,journals])
 const openCreate=()=>{setEditing(null);setModal(true)}; const remove=async(id:string)=>{if(!confirm(t('dataPage.confirmDelete')))return;setBusy(true);try{if(kind==='contacts')await deleteContact(id);if(kind==='products')await deleteProduct(id);await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{if(kind==='contacts'){const name=String(f.get('name')||''),mobile=String(f.get('mobile')||'')||undefined,person=f.get('kind')==='person',customer=f.get('customer')==='on',supplier=f.get('supplier')==='on';if(editing)await updateContact(editing.id,name,person?'person':'company',mobile,customer,supplier);else await createContact(name,person?'person':'company',mobile,customer,supplier)}else if(kind==='products'){const data=[String(f.get('sku')||''),String(f.get('barcode')||'')||undefined,String(f.get('name')||''),String(f.get('unit')||t('productForm.defaultUnit')),Number(f.get('sale')||0),Number(f.get('purchase')||0),Number(f.get('min')||0)] as const;if(editing&&'sku' in editing)await updateProduct(editing.id,...data);else await createProduct(...data)}else throw new Error(t('dataPage.notImplemented'));setModal(false);await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <section className="page"><div className="page-head"><div><div className="eyebrow">{t('dataPage.title')}</div><h1>{title}</h1><p>{t('dataPage.subtitle')}</p></div>{(kind==='contacts'||kind==='products')&&<button className="primary" onClick={openCreate}><Icon name="plus"/> {kind==='contacts'?t('dataPage.newParty'):t('dataPage.newProduct')}</button>}</div>{error&&<div className="error-box">{error}</div>}
 <div className="panel list-panel"><div className="toolbar"><div className="global-search inner"><Icon name="search" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`جستجو در ${title}...`}/></div><span className="row-count">{money(rows.length)} مورد</span><button aria-label={t('common.refresh')} className="icon-btn" onClick={load}><Icon name="refresh"/></button></div>
 {rows.length===0?<div className="empty-state"><Icon name="search"/><h3>{t('dataPage.noData')}</h3><p>{q?t('dataPage.noMatch'):t('dataPage.emptyYet')}</p></div>:<div className="table-wrap"><table className="large-table"><thead>{kind==='contacts'?<tr><th>{t('common.name')}</th><th>{t('common.type')}</th><th>{t('dataPage.mobile')}</th><th>{t('dataPage.role')}</th><th>{t('common.actions')}</th></tr>:kind==='products'?<tr><th>{t('invoiceForm.product')}</th><th>SKU</th><th>{t('common.unit')}</th><th>{t('dataPage.sale')}</th><th>{t('dataPage.minStock')}</th><th>{t('common.actions')}</th></tr>:kind==='accounts'?<tr><th>{t('common.code')}</th><th>{t('reports.account')}</th><th>{t('coa.level')}</th><th>{t('coa.nature')}</th></tr>:<tr><th>{t('common.number')}</th><th>{t('common.date')}</th><th>{t('common.description')}</th><th>{t('reports.debit')}</th><th>{t('reports.credit')}</th><th>{t('common.status')}</th></tr>}</thead><tbody>{rows.map((r:any)=><tr key={r.id}>{kind==='contacts'?<><td><b>{r.name}</b></td><td>{r.kind==='person'?t('dataPage.natural'):t('dataPage.legal')}</td><td>{r.mobile||'—'}</td><td>{r.is_customer&&r.is_supplier?t('dataPage.customerSupplier'):r.is_customer?t('partyForm.customer'):r.is_supplier?t('partyForm.supplier'):'—'}</td><td><button className="table-action" onClick={()=>{setEditing(r);setModal(true)}}>{t('common.editAction')}</button><button className="table-action danger-link" disabled={busy} onClick={()=>remove(r.id)}>{t('partyForm.remove')}</button></td></>:kind==='products'?<><td><b>{r.name}</b></td><td className="code">{r.sku}</td><td>{r.unit}</td><td>{money(r.sale_price)} ریال</td><td>{money(r.min_stock)}</td><td><button className="table-action" onClick={()=>{setEditing(r);setModal(true)}}>{t('common.editAction')}</button><button className="table-action danger-link" disabled={busy} onClick={()=>remove(r.id)}>{t('partyForm.remove')}</button></td></>:kind==='accounts'?<><td className="code">{r.code}</td><td><b>{r.name}</b></td><td>{r.level}</td><td>{r.nature}</td></>:<><td className="code">{r.number}</td><td>{r.entry_date}</td><td>{r.description}</td><td>{money(r.total_debit)}</td><td>{money(r.total_credit)}</td><td><span className={r.status==='posted'?'status done':'status pending'}>{r.status==='posted'?t('dataPage.posted'):r.status}</span></td></>}</tr>)}</tbody></table></div>}</div>
 {(kind==='contacts'||kind==='products')&&modal&&<div className="modal-backdrop" role="presentation"><form className="modal form-modal" onSubmit={submit}><div className="modal-head"><div><div className="eyebrow">{t('dataPage.realForm')}</div><h2>{editing?t('common.editAction'):t('dataPage.saveAction')} {kind==='contacts'?t('dataPage.person'):t('invoiceForm.product')}</h2></div><button aria-label={t('common.actions')} type="button" className="icon-btn" onClick={()=>setModal(false)}><Icon name="close"/></button></div>{kind==='contacts'?<div className="form-grid"><label>{t('common.name')}<input name="name" defaultValue={(editing as Contact|null)?.name||''} required/></label><label>{t('common.type')}<Select name="kind" defaultValue={(editing as Contact|null)?.kind||'person'}><option value="person">{t('dataPage.natural')}</option><option value="company">{t('dataPage.legal')}</option></Select></label><label>{t('dataPage.mobile')}<input name="mobile" defaultValue={(editing as Contact|null)?.mobile||''}/></label><label className="check-field"><input type="checkbox" name="customer" defaultChecked={(editing as Contact|null)?.is_customer}/> {t('partyForm.customer')}</label><label className="check-field"><input type="checkbox" name="supplier" defaultChecked={(editing as Contact|null)?.is_supplier}/> {t('partyForm.supplier')}</label></div>:<div className="form-grid"><label>{t('products.name')}<input name="name" defaultValue={(editing as Product|null)?.name||''} required/></label><label>SKU<input name="sku" defaultValue={(editing as Product|null)?.sku||''} required/></label><label>{t('productForm.barcode')}<input name="barcode" defaultValue={(editing as Product|null)?.barcode||''}/></label><label>{t('common.unit')}<input name="unit" defaultValue={(editing as Product|null)?.unit||t('productForm.defaultUnit')} required/></label><label>{t('dataPage.salePrice')}<input type="number" name="sale" defaultValue={(editing as Product|null)?.sale_price||0}/></label><label>{t('dataPage.purchasePrice')}<input type="number" name="purchase" defaultValue={(editing as Product|null)?.purchase_price||0}/></label><label>{t('dataPage.minStock')}<input type="number" name="min" defaultValue={(editing as Product|null)?.min_stock||0}/></label></div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(false)}>{t('common.cancel')}</button><button className="primary" disabled={busy}>{busy?t('ops.posting'):t('common.save')}</button></div></form></div>}
 </section>
}
