import {useEffect,useMemo,useState} from 'react'
import {Icon} from '../components/Icon'
import {Account,Journal,Product,StockBalance,Warehouse,getAccounts,getJournals,getProducts,getStockBalances,getWarehouses,createJournal,receiveStock,issueStock,transferStock,adjustStock,getStockCard,StockCardLine} from '../api'
import {errorText} from '../lib/errors'
import {formatRials as money, formatNumber as n, todayJalali} from '../lib/format'
import {useI18n} from '../lib/i18n'
import {Select} from '../components/Select'
type Mode='accounting'|'inventory'
export function Operations({mode}:{mode:Mode}){const {t}=useI18n();
 const [accounts,setAccounts]=useState<Account[]>([]),[journals,setJournals]=useState<Journal[]>([]),[products,setProducts]=useState<Product[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[balances,setBalances]=useState<StockBalance[]>([])
 const [q,setQ]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[modal,setModal]=useState(false),[action,setAction]=useState('receive'),[selectedProduct,setSelectedProduct]=useState(''),[selectedWarehouse,setSelectedWarehouse]=useState(''),[stockCard,setStockCard]=useState<StockCardLine[]>([])
 const load=async()=>{setError('');try{if(mode==='accounting'){setAccounts(await getAccounts());setJournals(await getJournals())}else{setProducts(await getProducts());setWarehouses(await getWarehouses());setBalances(await getStockBalances())}}catch(e){setError(errorText(e))}}
 useEffect(()=>{load()},[mode])
 const rows=useMemo(()=>{if(mode==='accounting')return journals.filter(x=>`${x.number} ${x.description} ${x.status}`.includes(q.trim())) as any[];return balances.filter(x=>{const p=products.find(y=>y.id===x.product_id);const w=warehouses.find(y=>y.id===x.warehouse_id);return `${p?.name||''} ${p?.sku||''} ${w?.name||''}`.includes(q.trim())})},[mode,q,journals,balances,products,warehouses])
 const openAction=(a:string)=>{setAction(a);setModal(true);setError('');setSuccess('')}
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');setSuccess('');try{const f=new FormData(e.currentTarget);if(mode==='accounting'){const date=String(f.get('date')||new Date().toISOString().slice(0,10)),desc=String(f.get('desc')||'');const a=String(f.get('debit')),b=String(f.get('credit')),amount=Number(f.get('amount')||0);if(!a||!b||a===b||amount<=0)throw new Error(t('ops.errAccounts'));await createJournal(date,desc,[[a,amount,0],[b,0,amount]]);setSuccess(t('ops.postedJournal'))}else{const p=String(f.get('product')),w=String(f.get('warehouse')),qty=Number(f.get('qty')||0),note=String(f.get('note')||'');if(!p||!w||qty<=0)throw new Error(t('ops.errInventory'));if(action==='receive')await receiveStock(p,w,qty,Number(f.get('cost')||0),note);if(action==='issue')await issueStock(p,w,qty,note);if(action==='transfer')await transferStock(p,w,String(f.get('toWarehouse')),qty,note);if(action==='adjust')await adjustStock(p,w,Number(f.get('newQty')||0),note);setSuccess(t('ops.postedInventory'))}setModal(false);await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 const showCard=async(p:string,w:string)=>{setSelectedProduct(p);setSelectedWarehouse(w);try{setStockCard(await getStockCard(p,w||undefined))}catch(e){setError(errorText(e))}}
 return <section className="page"><div className="page-head"><div><div className="eyebrow">{mode==='accounting'?t('nav.group.accounting'):t('common.warehouse')}</div><h1>{mode==='accounting'?t('ops.accountingTitle'):t('ops.inventoryTitle')}</h1><p>{mode==='accounting'?t('ops.accountingLead'):t('ops.inventoryLead')}</p></div><div className="quick-actions-inline">{mode==='accounting'?<button className="primary" onClick={()=>openAction('journal')}><Icon name="plus"/> {t('ops.newVoucher')}</button>:<><button className="secondary" onClick={()=>openAction('receive')}>{t('ops.goodsReceipt')}</button><button className="secondary" onClick={()=>openAction('issue')}>{t('ops.goodsIssue')}</button><button className="primary" onClick={()=>openAction('transfer')}>{t('ops.transferShort')}</button></>}</div></div>{error&&<div className="error-box">{error}</div>}{success&&<div className="success-box">{success}</div>}
 <div className="panel list-panel"><div className="toolbar"><div className="global-search inner"><Icon name="search" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t('ops.searchDots')}/></div><span className="row-count">{money(rows.length)} مورد</span><button aria-label={t('common.refresh')} className="icon-btn" onClick={load}><Icon name="refresh"/></button></div>
 {mode==='accounting'?<div className="table-wrap"><table className="large-table"><thead><tr><th>{t('common.number')}</th><th>{t('common.date')}</th><th>{t('common.description')}</th><th>{t('reports.debit')}</th><th>{t('reports.credit')}</th><th>{t('common.status')}</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td className="code">{r.number}</td><td>{r.entry_date}</td><td>{r.description||'—'}</td><td>{money(r.total_debit)}</td><td>{money(r.total_credit)}</td><td><span className={r.total_debit===r.total_credit?'status done':'status danger'}>{r.total_debit===r.total_credit?t('ops.balanced'):t('ops.unbalanced')}</span></td></tr>)}</tbody></table></div>:<div className="table-wrap"><table className="large-table"><thead><tr><th>{t('invoiceForm.product')}</th><th>{t('common.warehouse')}</th><th>{t('products.stock')}</th><th>{t('ops.reserved')}</th><th>{t('ops.available')}</th><th>{t('common.actions')}</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.product_id+'-'+r.warehouse_id}><td><b>{products.find(p=>p.id===r.product_id)?.name||r.product_id}</b></td><td>{warehouses.find(w=>w.id===r.warehouse_id)?.name||r.warehouse_id}</td><td>{money(r.quantity)}</td><td>{money(r.reserved_quantity)}</td><td className={r.available_quantity<0?'red-text':''}>{money(r.available_quantity)}</td><td><button className="table-action" onClick={()=>showCard(r.product_id,r.warehouse_id)}>{t('ops.itemCard')}</button><button className="table-action" onClick={()=>{setSelectedProduct(r.product_id);setSelectedWarehouse(r.warehouse_id);openAction('adjust')}}>{t('ops.adjustShort')}</button></td></tr>)}</tbody></table></div>}</div>
 {mode==='inventory'&&stockCard.length>0&&<div className="panel list-panel"><div className="toolbar"><b>{t('ops.itemCard')}</b><span className="row-count">{products.find(p=>p.id===selectedProduct)?.name||selectedProduct}</span></div><div className="table-wrap"><table className="large-table"><thead><tr><th>{t('common.date')}</th><th>{t('common.type')}</th><th>{t('common.quantity')}</th><th>{t('ops.unitCost')}</th><th>{t('common.description')}</th></tr></thead><tbody>{stockCard.map((x:any)=><tr key={x.id}><td>{x.movement_date}</td><td>{x.movement_type}</td><td>{money(x.quantity)}</td><td>{money(x.unit_cost)}</td><td>{x.note||'—'}</td></tr>)}</tbody></table></div></div>}
 {modal&&<div className="modal-backdrop" role="presentation"><form className="modal form-modal" onSubmit={submit}><div className="modal-head"><div><div className="eyebrow">{t('ops.realOperation')}</div><h2>{mode==='accounting'?t('ops.postJournal'):action==='receive'?t('ops.goodsReceipt'):action==='issue'?t('ops.goodsIssue'):action==='transfer'?t('ops.transfer'):t('ops.adjust')}</h2></div><button aria-label={t('common.actions')} type="button" className="icon-btn" onClick={()=>setModal(false)}><Icon name="close"/></button></div>{mode==='accounting'?<div className="form-grid"><label>{t('common.date')}<input name="date" defaultValue={todayJalali()} placeholder="1405/01/01" required/></label><label>{t('common.description')}<input name="desc" required/></label><label>{t('ops.debitAccount')}<Select name="debit" required><option value="">{t('ops.selectPlain')}</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</Select></label><label>{t('ops.creditAccount')}<Select name="credit" required><option value="">{t('ops.selectPlain')}</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</Select></label><label>{t('common.amount')}<input name="amount" type="number" min="1" required/></label></div>:<div className="form-grid"><label>{t('invoiceForm.product')}<Select name="product" value={selectedProduct} onChange={e=>setSelectedProduct(e.target.value)} required><option value="">{t('ops.selectPlain')}</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</Select></label><label>{t('common.warehouse')}<Select name="warehouse" value={selectedWarehouse} onChange={e=>setSelectedWarehouse(e.target.value)} required><option value="">{t('ops.selectPlain')}</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.code} — {w.name}</option>)}</Select></label>{action==='transfer'&&<label>{t('ops.destinationWarehouse')}<Select name="toWarehouse" required><option value="">{t('ops.selectPlain')}</option>{warehouses.filter(w=>w.id!==selectedWarehouse).map(w=><option key={w.id} value={w.id}>{w.code} — {w.name}</option>)}</Select></label>}{action==='adjust'?<label>{t('ops.newQuantity')}<input name="newQty" type="number" min="0" step="0.001" required/></label>:<label>{t('common.quantity')}<input name="qty" type="number" min="0.001" step="0.001" required/></label>}{action==='receive'&&<label>{t('ops.unitCost')}<input name="cost" type="number" min="0" defaultValue="0"/></label>}<label>{t('common.description')}<input name="note"/></label></div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(false)}>{t('common.cancel')}</button><button className="primary" disabled={busy}>{busy?t('ops.posting'):t('ops.postOperation')}</button></div></form></div>}
 </section>
}
