import {useEffect,useMemo,useState} from 'react'
import {Icon} from '../components/Icon'
import {Account,Journal,Product,StockBalance,Warehouse,getAccounts,getJournals,getProducts,getStockBalances,getWarehouses,createJournal,receiveStock,issueStock,transferStock,adjustStock,getStockCard,StockCardLine} from '../api'
import {errorText} from '../lib/errors'
import {formatRials as money, formatNumber as n} from '../lib/format'
type Mode='accounting'|'inventory'
export function Operations({mode}:{mode:Mode}){
 const [accounts,setAccounts]=useState<Account[]>([]),[journals,setJournals]=useState<Journal[]>([]),[products,setProducts]=useState<Product[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[balances,setBalances]=useState<StockBalance[]>([])
 const [q,setQ]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[modal,setModal]=useState(false),[action,setAction]=useState('receive'),[selectedProduct,setSelectedProduct]=useState(''),[selectedWarehouse,setSelectedWarehouse]=useState(''),[stockCard,setStockCard]=useState<StockCardLine[]>([])
 const load=async()=>{setError('');try{if(mode==='accounting'){setAccounts(await getAccounts());setJournals(await getJournals())}else{setProducts(await getProducts());setWarehouses(await getWarehouses());setBalances(await getStockBalances())}}catch(e){setError(errorText(e))}}
 useEffect(()=>{load()},[mode])
 const rows=useMemo(()=>{if(mode==='accounting')return journals.filter(x=>`${x.number} ${x.description} ${x.status}`.includes(q.trim())) as any[];return balances.filter(x=>{const p=products.find(y=>y.id===x.product_id);const w=warehouses.find(y=>y.id===x.warehouse_id);return `${p?.name||''} ${p?.sku||''} ${w?.name||''}`.includes(q.trim())})},[mode,q,journals,balances,products,warehouses])
 const openAction=(a:string)=>{setAction(a);setModal(true);setError('');setSuccess('')}
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');setSuccess('');try{const f=new FormData(e.currentTarget);if(mode==='accounting'){const date=String(f.get('date')||new Date().toISOString().slice(0,10)),desc=String(f.get('desc')||'');const a=String(f.get('debit')),b=String(f.get('credit')),amount=Number(f.get('amount')||0);if(!a||!b||a===b||amount<=0)throw new Error('ACC-UI-001: دو حساب متفاوت و مبلغ معتبر الزامی است.');await createJournal(date,desc,[[a,amount,0],[b,0,amount]]);setSuccess('سند متوازن با موفقیت ثبت شد.')}else{const p=String(f.get('product')),w=String(f.get('warehouse')),qty=Number(f.get('qty')||0),note=String(f.get('note')||'');if(!p||!w||qty<=0)throw new Error('INV-UI-001: کالا، انبار و مقدار معتبر الزامی است.');if(action==='receive')await receiveStock(p,w,qty,Number(f.get('cost')||0),note);if(action==='issue')await issueStock(p,w,qty,note);if(action==='transfer')await transferStock(p,w,String(f.get('toWarehouse')),qty,note);if(action==='adjust')await adjustStock(p,w,Number(f.get('newQty')||0),note);setSuccess('عملیات انبار با موفقیت ثبت شد.')}setModal(false);await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 const showCard=async(p:string,w:string)=>{setSelectedProduct(p);setSelectedWarehouse(w);try{setStockCard(await getStockCard(p,w||undefined))}catch(e){setError(errorText(e))}}
 return <section className="page"><div className="page-head"><div><div className="eyebrow">{mode==='accounting'?'ACCOUNTING':'INVENTORY'}</div><h1>{mode==='accounting'?'عملیات حسابداری':'عملیات انبار'}</h1><p>{mode==='accounting'?'ثبت سریع سند، کنترل تراز و مشاهده دفتر اسناد.':'کنترل موجودی، گردش کالا و عملیات واقعی انبار.'}</p></div><div className="quick-actions-inline">{mode==='accounting'?<button className="primary" onClick={()=>openAction('journal')}><Icon name="plus"/> سند جدید</button>:<><button className="secondary" onClick={()=>openAction('receive')}>رسید انبار</button><button className="secondary" onClick={()=>openAction('issue')}>حواله خروج</button><button className="primary" onClick={()=>openAction('transfer')}>انتقال</button></>}</div></div>{error&&<div className="error-box">{error}</div>}{success&&<div className="success-box">{success}</div>}
 <div className="panel list-panel"><div className="toolbar"><div className="global-search inner"><Icon name="search" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجو..."/></div><span className="row-count">{money(rows.length)} مورد</span><button className="icon-btn" onClick={load}><Icon name="refresh"/></button></div>
 {mode==='accounting'?<div className="table-wrap"><table className="large-table"><thead><tr><th>شماره</th><th>تاریخ</th><th>شرح</th><th>بدهکار</th><th>بستانکار</th><th>وضعیت</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td className="code">{r.number}</td><td>{r.entry_date}</td><td>{r.description||'—'}</td><td>{money(r.total_debit)}</td><td>{money(r.total_credit)}</td><td><span className={r.total_debit===r.total_credit?'status done':'status danger'}>{r.total_debit===r.total_credit?'متوازن':'نامتوازن'}</span></td></tr>)}</tbody></table></div>:<div className="table-wrap"><table className="large-table"><thead><tr><th>کالا</th><th>انبار</th><th>موجودی</th><th>رزرو</th><th>قابل فروش</th><th>عملیات</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.product_id+'-'+r.warehouse_id}><td><b>{products.find(p=>p.id===r.product_id)?.name||r.product_id}</b></td><td>{warehouses.find(w=>w.id===r.warehouse_id)?.name||r.warehouse_id}</td><td>{money(r.quantity)}</td><td>{money(r.reserved_quantity)}</td><td className={r.available_quantity<0?'red-text':''}>{money(r.available_quantity)}</td><td><button className="table-action" onClick={()=>showCard(r.product_id,r.warehouse_id)}>کارت کالا</button><button className="table-action" onClick={()=>{setSelectedProduct(r.product_id);setSelectedWarehouse(r.warehouse_id);openAction('adjust')}}>اصلاح</button></td></tr>)}</tbody></table></div>}</div>
 {mode==='inventory'&&stockCard.length>0&&<div className="panel list-panel"><div className="toolbar"><b>کارت کالا</b><span className="row-count">{products.find(p=>p.id===selectedProduct)?.name||selectedProduct}</span></div><div className="table-wrap"><table className="large-table"><thead><tr><th>تاریخ</th><th>نوع</th><th>مقدار</th><th>بهای واحد</th><th>شرح</th></tr></thead><tbody>{stockCard.map((x:any)=><tr key={x.id}><td>{x.movement_date}</td><td>{x.movement_type}</td><td>{money(x.quantity)}</td><td>{money(x.unit_cost)}</td><td>{x.note||'—'}</td></tr>)}</tbody></table></div></div>}
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(false)}><form className="modal form-modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">عملیات واقعی</div><h2>{mode==='accounting'?'ثبت سند حسابداری':action==='receive'?'رسید انبار':action==='issue'?'حواله خروج':action==='transfer'?'انتقال بین انبارها':'اصلاح موجودی'}</h2></div><button type="button" className="icon-btn" onClick={()=>setModal(false)}><Icon name="close"/></button></div>{mode==='accounting'?<div className="form-grid"><label>تاریخ<input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>شرح<input name="desc" required/></label><label>حساب بدهکار<select name="debit" required><option value="">انتخاب کنید</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>حساب بستانکار<select name="credit" required><option value="">انتخاب کنید</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>مبلغ<input name="amount" type="number" min="1" required/></label></div>:<div className="form-grid"><label>کالا<select name="product" value={selectedProduct} onChange={e=>setSelectedProduct(e.target.value)} required><option value="">انتخاب کنید</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select></label><label>انبار<select name="warehouse" value={selectedWarehouse} onChange={e=>setSelectedWarehouse(e.target.value)} required><option value="">انتخاب کنید</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.code} — {w.name}</option>)}</select></label>{action==='transfer'&&<label>انبار مقصد<select name="toWarehouse" required><option value="">انتخاب کنید</option>{warehouses.filter(w=>w.id!==selectedWarehouse).map(w=><option key={w.id} value={w.id}>{w.code} — {w.name}</option>)}</select></label>}{action==='adjust'?<label>موجودی جدید<input name="newQty" type="number" min="0" step="0.001" required/></label>:<label>مقدار<input name="qty" type="number" min="0.001" step="0.001" required/></label>}{action==='receive'&&<label>بهای واحد<input name="cost" type="number" min="0" defaultValue="0"/></label>}<label>شرح<input name="note"/></label></div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(false)}>انصراف</button><button className="primary" disabled={busy}>{busy?'در حال ثبت...':'ثبت عملیات'}</button></div></form></div>}
 </section>
}
