import {useEffect,useState} from 'react'
import {Icon} from '../components/Icon'
import {deletePrintTemplate,getPrintTemplates,PrintTemplate,savePrintTemplate} from '../api'
import {errorText} from '../lib/errors'
export function PrintTemplates(){
 const [items,setItems]=useState<PrintTemplate[]>([]);const [editing,setEditing]=useState<PrintTemplate|null>(null);const [name,setName]=useState('قالب جدید');const [type,setType]=useState('invoice');const [html,setHtml]=useState('<section dir="rtl"><h1>{{company.name}}</h1><h2>{{invoice.number}}</h2>{{#lines}}<div>{{product.name}} — {{quantity}} — {{line_total}}</div>{{/lines}}<strong>{{invoice.total}}</strong></section>');const [def,setDef]=useState(false);const [msg,setMsg]=useState('');const [error,setError]=useState('')
 const load=async()=>{try{setItems(await getPrintTemplates())}catch(e){setError(errorText(e))}};useEffect(()=>{load()},[])
 const edit=(x:PrintTemplate)=>{setEditing(x);setName(x.name);setType(x.template_type);setHtml(x.content_html);setDef(x.is_default)}
 const save=async()=>{try{await savePrintTemplate(editing?.id,name,type,html,def);setMsg('قالب ذخیره شد.');setEditing(null);await load()}catch(e){setError(errorText(e))}}
 const remove=async(id:string)=>{if(!confirm('قالب حذف شود؟'))return;try{await deletePrintTemplate(id);await load()}catch(e){setError(errorText(e))}}
 return <section className="page"><div className="page-head"><div><div className="eyebrow">قالب‌های چاپ</div><h1>قالب‌های چاپ</h1><p>قالب فاکتور، رسید، سند، گزارش و برچسب را مدیریت کنید.</p></div><button className="primary" onClick={()=>{setEditing(null);setName('قالب جدید');setHtml('<section dir="rtl"><h1>{{company.name}}</h1></section>')}}>قالب جدید</button></div>{error&&<div className="error-box">{error}</div>}{msg&&<div className="success-box">{msg}</div>}<div className="builder-grid"><div className="panel"><div className="builder-section"><label>نام<input value={name} onChange={e=>setName(e.target.value)}/></label><label>نوع<select value={type} onChange={e=>setType(e.target.value)}><option value="invoice">فاکتور</option><option value="receipt">رسید</option><option value="journal">سند حسابداری</option><option value="report">گزارش</option><option value="label">برچسب</option></select></label></div><label>قالب HTML<textarea className="template-editor" value={html} onChange={e=>setHtml(e.target.value)} rows={16}/></label><label className="check-row"><input type="checkbox" checked={def} onChange={e=>setDef(e.target.checked)}/> قالب پیش‌فرض</label><button className="primary" onClick={save}>ذخیره قالب</button></div><div className="panel saved-reports"><div className="panel-head"><h3>قالب‌های موجود</h3></div>{items.length?items.map(x=><div className="saved-report" key={x.id}><button onClick={()=>edit(x)}>{x.name}<small>{x.template_type}{x.is_default?' — پیش‌فرض':''}</small></button><button className="danger-link" onClick={()=>remove(x.id)}>حذف</button></div>):<div className="empty">قالبی ثبت نشده است.</div>}</div></div></section>
}
