import {useEffect,useState} from 'react'
import {Icon} from '../components/Icon'
import {getAccountLedgerSummary,getInventoryValuation,getPurchaseReport,getSalesReport,getProfitLoss,getTrialBalance,getReceivables,getPayables,getCashPosition,getJournalBook,getFinancialStatement,getPartyAging,SalesReportRow,PurchaseReportRow,InventoryValuation,AccountLedgerSummary,ProfitLoss,TrialBalance,PartyBalance,CashPosition,JournalBookLine,FinancialStatement,PartyAging} from '../api'
const money=(n:number)=>new Intl.NumberFormat('fa-IR').format(Math.round(n))
const today=()=>new Date().toISOString().slice(0,10)
type Kind='sales'|'purchase'|'inventory'|'ledger'|'trial'|'profit'|'receivable'|'payable'|'cash'|'journal'|'balance'|'income'|'agingReceivable'|'agingPayable'
export function Reports(){
 const [kind,setKind]=useState<Kind>('sales');const [from,setFrom]=useState('');const [to,setTo]=useState(today());const [sales,setSales]=useState<SalesReportRow[]>([]);const [purchase,setPurchase]=useState<PurchaseReportRow[]>([]);const [inventory,setInventory]=useState<InventoryValuation[]>([]);const [ledger,setLedger]=useState<AccountLedgerSummary[]>([]);const [trial,setTrial]=useState<TrialBalance>();const [profit,setProfit]=useState<ProfitLoss>();const [receivable,setReceivable]=useState<PartyBalance[]>([]);const [payable,setPayable]=useState<PartyBalance[]>([]);const [cash,setCash]=useState<CashPosition>();const [journal,setJournal]=useState<JournalBookLine[]>([]);const [balance,setBalance]=useState<FinancialStatement>();const [income,setIncome]=useState<FinancialStatement>();const [agingR,setAgingR]=useState<PartyAging[]>([]);const [agingP,setAgingP]=useState<PartyAging[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{if(kind==='sales')setSales(await getSalesReport(from||undefined,to||undefined));else if(kind==='purchase')setPurchase(await getPurchaseReport(from||undefined,to||undefined));else if(kind==='inventory')setInventory(await getInventoryValuation());else if(kind==='ledger')setLedger(await getAccountLedgerSummary(from||undefined,to||undefined));else if(kind==='trial')setTrial(await getTrialBalance());else if(kind==='profit')setProfit(await getProfitLoss());else if(kind==='receivable')setReceivable(await getReceivables());else if(kind==='payable')setPayable(await getPayables());else if(kind==='cash')setCash(await getCashPosition());else if(kind==='journal')setJournal(await getJournalBook(from||undefined,to||undefined));else if(kind==='balance')setBalance(await getFinancialStatement('balance_sheet',to||undefined));else if(kind==='income')setIncome(await getFinancialStatement('income_statement',to||undefined));else if(kind==='agingReceivable')setAgingR(await getPartyAging(true,to||undefined));else setAgingP(await getPartyAging(false,to||undefined))}catch(e){setError(String(e))}finally{setLoading(false)}}
 useEffect(()=>{load()},[kind])
 const tabs:[Kind,string][]=[['sales','فروش'],['purchase','خرید'],['inventory','موجودی'],['ledger','گردش حساب'],['trial','تراز آزمایشی'],['profit','سود و زیان'],['receivable','مطالبات'],['payable','بدهی‌ها'],['cash','نقدینگی'],['journal','دفتر روزنامه'],['balance','ترازنامه'],['income','سود و زیان تفصیلی'],['agingReceivable','سن مطالبات'],['agingPayable','سن بدهی‌ها']]
 return <section className="page"><div className="page-head"><div><div className="eyebrow">گزارش‌های واقعی</div><h1>مرکز گزارشات</h1><p>تمام ارقام از داده‌های ثبت‌شده و اسناد Posted خوانده می‌شوند.</p></div><button className="primary" onClick={load}><Icon name="refresh"/> بروزرسانی</button></div>
  <div className="panel list-panel"><div className="toolbar"><div className="report-tabs">{tabs.map(([id,label])=><button key={id} className={kind===id?'active':''} onClick={()=>setKind(id)}>{label}</button>)}</div><label className="date-filter">از <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="date-filter">تا <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="filter-btn" onClick={load}><Icon name="filter"/> اعمال</button></div>
  {error&&<div className="error-box">{error}</div>}{loading?<div className="empty-state"><p>در حال محاسبه گزارش...</p></div>:<>
  {kind==='sales'&&<Table headers={['تاریخ','شماره','مشتری','خالص','مالیات','مبلغ','تسویه']} rows={sales.map(x=>[x.date,x.invoice_number,x.contact_name||'بدون شخص',money(x.subtotal-x.discount),money(x.tax),money(x.total),status(x.payment_status)])}/>}
  {kind==='purchase'&&<Table headers={['تاریخ','شماره','تأمین‌کننده','خالص','مالیات','مبلغ','تسویه']} rows={purchase.map(x=>[x.date,x.invoice_number,x.contact_name||'بدون شخص',money(x.subtotal-x.discount),money(x.tax),money(x.total),status(x.payment_status)])}/>}
  {kind==='inventory'&&<Table headers={['کالا','انبار','موجودی','میانگین بها','ارزش']} rows={inventory.map(x=>[x.product_name,x.warehouse_name,money(x.quantity),money(x.average_cost),money(x.value)])}/>}
  {kind==='ledger'&&<Table headers={['کد','حساب','بدهکار','بستانکار','مانده']} rows={ledger.map(x=>[x.code,x.name,money(x.debit),money(x.credit),`${money(Math.abs(x.balance))} ${x.balance>=0?'بدهکار':'بستانکار'}`])}/>}
  {kind==='trial'&&trial&&<><div className="metric-strip"><div><span>جمع بدهکار</span><b>{money(trial.total_debit)} ریال</b></div><div><span>جمع بستانکار</span><b>{money(trial.total_credit)} ریال</b></div><div><span>کنترل توازن</span><b className="green-text">{trial.total_debit===trial.total_credit?'متوازن':'نامتوازن'}</b></div></div><Table headers={['کد','حساب','بدهکار','بستانکار','مانده']} rows={trial.accounts.map(x=>[x.code,x.name,money(x.debit),money(x.credit),money(Math.abs(x.balance))])}/></>}
  {kind==='profit'&&profit&&<div className="stats-grid"><Stat title="درآمد فروش" value={profit.revenue}/><Stat title="برگشت فروش" value={profit.sales_returns}/><Stat title="درآمد خالص" value={profit.net_revenue}/><Stat title="بهای تمام‌شده" value={profit.cogs}/><Stat title="سود ناخالص" value={profit.gross_profit}/><Stat title="حاشیه سود" value={profit.gross_margin_percent} unit="٪"/></div>}
  {kind==='receivable'&&<Table headers={['مشتری','تعداد فاکتور','فروش','تسویه','مانده']} rows={receivable.map(x=>[x.contact_name,x.invoice_count,money(x.invoiced),money(x.settled),money(x.remaining)])}/>}
  {kind==='payable'&&<Table headers={['تأمین‌کننده','تعداد فاکتور','خرید','تسویه','مانده']} rows={payable.map(x=>[x.contact_name,x.invoice_count,money(x.invoiced),money(x.settled),money(x.remaining)])}/>}
  {kind==='cash'&&cash&&<><div className="metric-strip"><div><span>نقدینگی کل</span><b>{money(cash.total)} ریال</b></div></div><Table headers={['حساب','نوع','مانده']} rows={cash.accounts.map(x=>[x.name,x.account_type==='bank'?'بانک':x.account_type==='cash'?'صندوق':'تنخواه',money(x.balance)])}/></>}
  {kind==='journal'&&<Table headers={['تاریخ','شماره','شرح','کد حساب','حساب','بدهکار','بستانکار']} rows={journal.map(x=>[x.date,x.number,x.description,x.account_code,x.account_name,money(x.debit),money(x.credit)])}/>}
  {kind==='balance'&&balance&&<><div className="metric-strip"><div><span>تاریخ گزارش</span><b>{balance.as_of}</b></div><div><span>جمع اقلام</span><b>{money(balance.total)} ریال</b></div></div><Table headers={['کد','حساب','ماهیت','مبلغ']} rows={balance.lines.map(x=>[x.code,x.name,x.nature,money(Math.abs(x.amount))])}/></>}
  {kind==='income'&&income&&<><div className="metric-strip"><div><span>تاریخ گزارش</span><b>{income.as_of}</b></div><div><span>جمع اقلام</span><b>{money(income.total)} ریال</b></div></div><Table headers={['کد','حساب','ماهیت','مبلغ']} rows={income.lines.map(x=>[x.code,x.name,x.nature,money(Math.abs(x.amount))])}/></>}
  {kind==='agingReceivable'&&<Table headers={['مشتری','جاری','1-30','31-60','61-90','بیش از 90','جمع']} rows={agingR.map(x=>[x.contact_name,money(x.current),money(x.days_1_30),money(x.days_31_60),money(x.days_61_90),money(x.over_90),money(x.total)])}/>}
  {kind==='agingPayable'&&<Table headers={['تأمین‌کننده','جاری','1-30','31-60','61-90','بیش از 90','جمع']} rows={agingP.map(x=>[x.contact_name,money(x.current),money(x.days_1_30),money(x.days_31_60),money(x.days_61_90),money(x.over_90),money(x.total)])}/> }
  </>}</div></section>
}
function status(v:string){return v==='paid'?'تسویه شده':v==='partial'?'تسویه جزئی':'تسویه نشده'}
function Stat({title,value,unit='ریال'}:{title:string,value:number,unit?:string}){return <div className="stat-card"><span className="stat-title">{title}</span><strong>{money(value)}<small>{unit}</small></strong></div>}
function Table({headers,rows}:{headers:string[],rows:(string|number)[][]}){return <div className="table-wrap"><table className="large-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{j===0?<b>{v}</b>:v}</td>)}</tr>):<tr><td colSpan={headers.length}><div className="empty-state"><p>داده‌ای برای نمایش وجود ندارد.</p></div></td></tr>}</tbody></table></div>}
