import {useEffect,useMemo,useState} from 'react'
import {getAccountLedgerSummary,getInventoryValuation,getPurchaseReport,getSalesReport,listCustomReports,saveCustomReport,deleteCustomReport,SalesReportRow,PurchaseReportRow,InventoryValuation,AccountLedgerSummary} from '../api'
import {Icon} from '../components/Icon'

type Source='sales'|'purchase'|'inventory'|'ledger'
type Row=Record<string,string|number>
type Column={key:string,label:string}
type Config={columns:string[],filter:string,sortKey:string,sortDir:'asc'|'desc',groupKey:string,from:string,to:string}
type Saved={id:string,name:string,source:string,config_json:string}
const sourceLabels:Record<Source,string>={sales:'گزارش فروش',purchase:'گزارش خرید',inventory:'ارزش موجودی',ledger:'گردش حساب'}
const columns:Record<Source,Column[]>={sales:[['date','تاریخ'],['invoice_number','شماره'],['contact_name','شخص'],['subtotal','خالص'],['discount','تخفیف'],['tax','مالیات'],['total','مبلغ'],['payment_status','وضعیت']].map(([key,label])=>({key,label})),purchase:[['date','تاریخ'],['invoice_number','شماره'],['contact_name','تأمین‌کننده'],['subtotal','خالص'],['discount','تخفیف'],['tax','مالیات'],['total','مبلغ'],['payment_status','وضعیت']].map(([key,label])=>({key,label})),inventory:[['product_name','کالا'],['warehouse_name','انبار'],['quantity','موجودی'],['average_cost','میانگین بها'],['value','ارزش']].map(([key,label])=>({key,label})),ledger:[['code','کد'],['name','حساب'],['debit','بدهکار'],['credit','بستانکار'],['balance','مانده']].map(([key,label])=>({key,label}))}
const today=()=>new Date().toISOString().slice(0,10)
const money=(n:number)=>new Intl.NumberFormat('fa-IR').format(Math.round(n))
const escapeHtml=(v:string)=>v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')
function normalize(source:Source,data:unknown):Row[]{if(source==='sales'||source==='purchase')return(data as(SalesReportRow|PurchaseReportRow)[]).map(x=>({...x,contact_name:x.contact_name||'بدون شخص'}));if(source==='inventory')return(data as InventoryValuation[]).map(x=>({...x}));return(data as AccountLedgerSummary[]).map(x=>({...x}))}
function download(name:string,content:string,type:string){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function csv(rows:Row[],cols:Column[]){const q=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;return'\ufeff'+[cols.map(c=>q(c.label)).join(','),...rows.map(r=>cols.map(c=>q(r[c.key])).join(','))].join('\r\n')}
function printReport(name:string,sourceLabel:string,period:string,rows:Row[],cols:Column[]){const w=window.open('','_blank','width=1100,height=800');if(!w)return false;const d=w.document;d.title=name;d.documentElement.dir='rtl';const meta=d.createElement('meta');meta.charSet='utf-8';d.head.appendChild(meta);const style=d.createElement('style');style.textContent='body{font-family:Tahoma,Arial;padding:28px;color:#21254E}h1{font-size:20px}p{color:#62748E}table{width:100%;border-collapse:collapse}th,td{border:1px solid #d9dfe9;padding:8px;text-align:right}th{background:#F6F9FF}@media print{button{display:none}}';d.head.appendChild(style);const h=d.createElement('h1');h.textContent=name;d.body.appendChild(h);const p=d.createElement('p');p.textContent=`${sourceLabel} | ${period}`;d.body.appendChild(p);const table=d.createElement('table');const thead=d.createElement('thead');const headRow=d.createElement('tr');cols.forEach(c=>{const th=d.createElement('th');th.textContent=c.label;headRow.appendChild(th)});thead.appendChild(headRow);table.appendChild(thead);const tbody=d.createElement('tbody');rows.forEach(r=>{const tr=d.createElement('tr');cols.forEach(c=>{const td=d.createElement('td');td.textContent=String(r[c.key]??'');tr.appendChild(td)});tbody.appendChild(tr)});table.appendChild(tbody);d.body.appendChild(table);w.focus();setTimeout(()=>w.print(),150);return true}

export function ReportBuilder(){
 const[source,setSource]=useState<Source>('sales');const[data,setData]=useState<Row[]>([]);const[config,setConfig]=useState<Config>({columns:columns.sales.map(c=>c.key),filter:'',sortKey:'',sortDir:'asc',groupKey:'',from:'',to:today()});const[name,setName]=useState('گزارش سفارشی');const[saved,setSaved]=useState<Saved[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const available=columns[source]
 const loadSource=async(s:Source)=>{setLoading(true);setError('');try{const d=s==='sales'?await getSalesReport(config.from||undefined,config.to||undefined):s==='purchase'?await getPurchaseReport(config.from||undefined,config.to||undefined):s==='inventory'?await getInventoryValuation():await getAccountLedgerSummary(config.from||undefined,config.to||undefined);setData(normalize(s,d))}catch{setError('بارگذاری گزارش انجام نشد')}finally{setLoading(false)}}
 useEffect(()=>{setConfig(c=>({...c,columns:columns[source].map(x=>x.key),sortKey:'',groupKey:''}));loadSource(source)},[source])
 const refreshSaved=async()=>{try{setSaved(await listCustomReports())}catch{setError('بارگذاری گزارش‌های ذخیره‌شده انجام نشد')}};useEffect(()=>{refreshSaved()},[])
 const result=useMemo(()=>{let r=data.filter(row=>!config.filter||Object.values(row).some(v=>String(v??'').toLowerCase().includes(config.filter.toLowerCase())));if(config.sortKey)r=[...r].sort((a,b)=>{const cmp=String(a[config.sortKey]??'').localeCompare(String(b[config.sortKey]??''),'fa',{numeric:true});return config.sortDir==='asc'?cmp:-cmp});return r},[data,config.filter,config.sortKey,config.sortDir])
 const selected=available.filter(c=>config.columns.includes(c.key));const grouped=useMemo(()=>{if(!config.groupKey)return[{key:'',rows:result}];const m=new Map<string,Row[]>();for(const row of result){const k=String(row[config.groupKey]??'—');if(!m.has(k))m.set(k,[]);m.get(k)!.push(row)}return[...m].map(([key,rows])=>({key,rows}))},[result,config.groupKey])
 const save=async()=>{try{setError('');await saveCustomReport(undefined,name,source,JSON.stringify(config));await refreshSaved()}catch{setError('ذخیره گزارش انجام نشد')}};const remove=async(id:string)=>{try{await deleteCustomReport(id);await refreshSaved()}catch{setError('حذف گزارش انجام نشد')}};const loadSaved=(x:Saved)=>{try{setName(x.name);setSource(x.source as Source);setConfig(JSON.parse(x.config_json) as Config)}catch{setError('تنظیمات گزارش ذخیره‌شده نامعتبر است')}};const exportCsv=()=>download(`${name}.csv`,csv(result,selected),'text/csv;charset=utf-8');const exportExcel=()=>{const html=`<html><head><meta charset="utf-8"></head><body dir="rtl"><table border="1"><thead><tr>${selected.map(c=>`<th>${escapeHtml(c.label)}</th>`).join('')}</tr></thead><tbody>${result.map(r=>`<tr>${selected.map(c=>`<td>${escapeHtml(String(r[c.key]??''))}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`;download(`${name}.xls`,html,'application/vnd.ms-excel;charset=utf-8')};const print=()=>{if(!printReport(name,sourceLabels[source],`${config.from||'ابتدا'} تا ${config.to||'امروز'}`,result,selected))setError('پنجره چاپ توسط سیستم مسدود شد')}
 return <section className="page"><div className="page-head"><div><div className="eyebrow">گزارش‌ساز حرفه‌ای</div><h1>Report Builder</h1><p>گزارش را بساز، ذخیره کن و خروجی بگیر.</p></div><div className="quick-actions-inline"><button className="secondary" onClick={()=>loadSource(source)}><Icon name="refresh"/> بروزرسانی</button><button className="primary" onClick={save}>ذخیره گزارش</button></div></div>{error&&<div className="error-box">{error}</div>}
 <div className="builder-grid"><div className="panel builder-controls"><div className="builder-section"><label>نام گزارش<input value={name} onChange={e=>setName(e.target.value)}/></label><label>منبع<select value={source} onChange={e=>setSource(e.target.value as Source)}>{Object.entries(sourceLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><div className="builder-section"><label>جستجوی عمومی<input value={config.filter} onChange={e=>setConfig({...config,filter:e.target.value})} placeholder="فیلتر متن..."/></label><label>از<input type="date" value={config.from} onChange={e=>setConfig({...config,from:e.target.value})}/></label><label>تا<input type="date" value={config.to} onChange={e=>setConfig({...config,to:e.target.value})}/></label></div><div className="builder-section"><label>مرتب‌سازی<select value={config.sortKey} onChange={e=>setConfig({...config,sortKey:e.target.value})}><option value="">بدون مرتب‌سازی</option>{available.map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select></label><label>جهت<select value={config.sortDir} onChange={e=>setConfig({...config,sortDir:e.target.value as 'asc'|'desc'})}><option value="asc">صعودی</option><option value="desc">نزولی</option></select></label><label>گروه‌بندی<select value={config.groupKey} onChange={e=>setConfig({...config,groupKey:e.target.value})}><option value="">بدون گروه‌بندی</option>{available.map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select></label></div><div><strong>ستون‌ها</strong><div className="column-picks">{available.map(c=><label key={c.key}><input type="checkbox" checked={config.columns.includes(c.key)} onChange={e=>setConfig({...config,columns:e.target.checked?[...config.columns,c.key]:config.columns.filter(x=>x!==c.key)})}/>{c.label}</label>)}</div></div><div className="export-actions"><button onClick={exportCsv}>CSV</button><button onClick={exportExcel}>Excel</button><button onClick={print}>چاپ / PDF</button></div></div>
 <div className="panel saved-reports"><div className="panel-head"><h3>گزارش‌های ذخیره‌شده</h3></div>{saved.length?saved.map(x=><div className="saved-report" key={x.id}><button onClick={()=>loadSaved(x)}>{x.name}<small>{sourceLabels[x.source as Source]||x.source}</small></button><button className="danger-link" onClick={()=>remove(x.id)}>حذف</button></div>):<div className="empty">گزارش ذخیره‌شده‌ای وجود ندارد.</div>}</div></div>
 <div className="panel report-preview"><div className="panel-head"><h3>پیش‌نمایش</h3><span>{result.length} ردیف</span></div>{loading?<div className="empty-state">در حال آماده‌سازی...</div>:<div className="table-wrap"><table className="large-table"><thead><tr>{selected.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{grouped.map(g=><>{g.key&&<tr className="group-row"><td colSpan={selected.length}><b>{g.key}</b> — {g.rows.length} ردیف</td></tr>}{g.rows.map((r,i)=><tr key={`${g.key}-${i}`}>{selected.map(c=><td key={c.key}>{typeof r[c.key]==='number'?money(r[c.key] as number):String(r[c.key]??'')}</td>)}</tr>)}</>)}</tbody></table></div>}</div></section>
}
